Fix installing Google Cloud CLI in GitHub deployment workflow
Should fixes this error:

ERROR: (gcloud.components.install)
You cannot perform this action because the Google Cloud CLI component manager
is disabled for this installation. You can run the following command
to achieve the same result for this installation:
sudo apt-get install google-cloud-cli